name: sparetime
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  usage_stats: ^1.3.1

  device_apps:
    path: ./plugins/device_apps   # 👈 Local override

  provider: ^6.0.0  
  google_mobile_ads: ^5.0.0
  share_plus: ^7.0.0
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

